### ISSUE TITLE
pvl

### ISSUE THREAD

**Issue by michaelaye** [cmillion/pds-util#1]
Hi! 

Just wondered why you had your own `pvl` implementation implemented? Possibly because the old one in the planetarypy GH org wasn't really Python 3 ready? or kinda-half baked? I think thanks to Ross' upgrades, that should be better now. maybe worth checking, if it's possible to remove a big bunch of code of your repo.

**Comment by cmillion** [comment]
I don't remember why I did that. I think that it was simpler for me, for some reason, and that maybe I also wanted to fiddle with the PVL code, particularly how the output data with structured. I ended up writing a wrapper to PVL that converts the output to a `dict()` if desired. I didn't realize, at first, that this breaks pretty often because PDS3 allowed duplicate label names at the same level of nesting. I also did not know, at the time, that PVL was being revised.
